services:
  - type: web
    name: probanker-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: probanker-db
          property: connectionString

databases:
  - name: probanker-db
    plan: free
    env: python